-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES AS BS
LEFT JOIN BOOK AS B
ON BS.BOOK_ID = B.BOOK_ID
LEFT JOIN AUTHOR AS A
ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE BS.SALES_DATE	LIKE '2022-01%'
GROUP BY A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC 