-- 코드를 입력하세요
SELECT GU.USER_ID, GU.NICKNAME, CONCAT(GU.CITY, ' ', GU.STREET_ADDRESS1, ' ', GU.STREET_ADDRESS2) AS 전체주소,
CONCAT(SUBSTRING(TLNO, 1, 3), '-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_BOARD AS GB
LEFT JOIN USED_GOODS_USER AS GU 
ON GB.WRITER_ID = GU.USER_ID
GROUP BY GU.USER_ID
HAVING COUNT(GU.USER_ID) >= 3
ORDER BY GU.USER_ID DESC;