-- 코드를 입력하세요
SELECT YEAR(sales_date) AS YEAR, MONTH(sales_date) AS MONTH, GENDER, COUNT(DISTINCT OS.user_id) AS USERS
FROM ONLINE_SALE AS OS
LEFT JOIN USER_INFO AS UI
ON OS.USER_ID = UI.USER_ID
WHERE gender IS NOT NULL
GROUP BY YEAR(sales_date), MONTH(sales_date), gender
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;