-- 코드를 작성해주세요
WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT A.ID, A.PARENT_ID, GENERATION + 1
    FROM ECOLI_DATA AS A
    JOIN CTE AS C
    ON A.PARENT_ID = C.ID)
    
SELECT COUNT(C.ID) AS 'COUNT', GENERATION
FROM CTE AS C
LEFT JOIN ECOLI_DATA AS ED
ON C.ID = ED.PARENT_ID
WHERE ED.ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION ASC;