-- 코드를 입력하세요
SELECT FLAVOR
FROM  (SELECT A.FLAVOR, SUM(A.TOTAL_ORDER) + SUM(B.TOTAL_ORDER) as SUM
       FROM FIRST_HALF AS A
       LEFT JOIN JULY AS B
       ON A.FLAVOR = B.FLAVOR
       GROUP BY A.FLAVOR
       ORDER BY SUM DESC) AS C
LIMIT 3;