-- 코드를 입력하세요
SELECT BOA.WRITER_ID, US.NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS BOA
LEFT JOIN USED_GOODS_USER AS US
ON BOA.WRITER_ID = US.USER_ID
WHERE BOA.STATUS = 'DONE'
GROUP BY BOA.WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;