-- 코드를 입력하세요
SELECT MONTH(start_date) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT car_id
                     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                     WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
                     GROUP BY car_id
                     HAVING COUNT(CAR_ID) >= 5) AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(start_date), CAR_ID
ORDER BY MONTH(start_date) ASC, CAR_ID DESC;