-- 코드를 작성해주세요
SELECT FI.ID, FN.FISH_NAME, FI.LENGTH
FROM FISH_INFO AS FI
LEFT JOIN FISH_NAME_INFO AS FN
ON FI.FISH_TYPE = FN.FISH_TYPE
WHERE (FN.FISH_NAME, FI.LENGTH) IN (SELECT FISH_NAME, MAX(LENGTH) AS LENGTH
                            FROM FISH_INFO AS FI
                            LEFT JOIN FISH_NAME_INFO AS FN
                            ON FI.FISH_TYPE = FN.FISH_TYPE
                            GROUP BY FISH_NAME)
ORDER BY FI.ID ASC;
