-- 코드를 작성해주세요
SELECT SUM(GR.SCORE) AS SCORE,  GR.EMP_NO, EM.EMP_NAME,EM.POSITION, EM.EMAIL
FROM HR_EMPLOYEES AS EM
LEFT JOIN HR_DEPARTMENT AS DE
ON EM.DEPT_ID = DE.DEPT_ID
LEFT JOIN HR_GRADE AS GR
ON EM.EMP_NO = GR.EMP_NO
GROUP BY EM.EMP_NAME,  GR.EMP_NO, EM.POSITION, EM.EMAIL
ORDER BY SCORE DESC
LIMIT 1;