-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', GF.BOARD_ID, '/', GF.FILE_ID, GF.FILE_NAME, GF.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS GB
LEFT JOIN USED_GOODS_FILE AS GF
ON GB.BOARD_ID = GF.BOARD_ID
WHERE VIEWS IN (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)