-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM (SELECT UB.VIEWS, UF.FILE_ID, UF.FILE_EXT, UF.FILE_NAME, UF.BOARD_ID
      FROM USED_GOODS_BOARD AS UB
      LEFT JOIN USED_GOODS_FILE AS UF
      ON UB.BOARD_ID = UF.BOARD_ID) AS D
WHERE VIEWS IN (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC;