-- 코드를 입력하세요
WITH RECURSIVE CTE AS (
    SELECT 0 AS PRICE_GROUP
    UNION ALL
    SELECT PRICE_GROUP + 10000
    FROM CTE
    WHERE PRICE_GROUP < (SELECT MAX(P.PRICE) FROM PRODUCT AS P))

SELECT P.PRICE_GROUP, COUNT(P.PRICE_GROUP) AS PRODUCTS
FROM (SELECT TRUNCATE(PRICE, -4) AS PRICE_GROUP
      FROM PRODUCT) AS P
LEFT JOIN CTE
ON P.PRICE_GROUP = CTE.PRICE_GROUP
GROUP BY P.PRICE_GROUP
ORDER BY PRICE_GROUP ASC;


